### ISSUE TITLE
Cannot delete

### ISSUE THREAD

**Issue by jdelafon** [voidcontext/slick-generic-dao-example#1]
Passing `driver` to the `Repository` directly, you cannot use `.delete` to provide a common `deleteById` method, because it is missing implicits. 
(Too bad, it is the only version of a generic DAO that I could understand and make work so far.)

**Comment by voidcontext** [comment]
Can you please provide a test case which fails? 

Also, implementing a general/abstract repository is not a good idea. I wrote this code long ago... today probably I wouldn't implement a general abstract repository, but a user specific repository and an interface for that repo. But this is probably a different discussion.

If you could provide a failing ScalaTest case I'd have a look at it.

**Comment by jdelafon** [comment]
I meant that if one wants to add this to the Repository, it will miss implicits:

```
  def deleteById(id: Id): Future[Int] = db run filterById(id).delete
```

It says "value delete is not a member of slick.lifted.Query".

There are many issues open here and there about it, for instance:
https://groups.google.com/forum/#!searchin/scalaquery/delete%7Csort:relevance/scalaquery/JMnNfuPL8T4/-wo_GyX0JgAJ

In all honesty, about the test case, no; I am already getting crazy with all this obscure typing in my own project. I am building a LIMS, so everything is about CRUD operations onto 120 different tables. If a general repository is a bad idea, I'd really be interested in knowing your point of view about the better way.

**Comment by voidcontext** [comment]
Thanks, for the example I was able to reproduce the error... I'm thinking about the resolution. I don't have any good idea yet but I'm working on it.

I wasn't exact enough in my previous comment. It's not that it's not a good idea, but it's depending on your domain. Usually I'm working with complex domains, where such a generalisation doesn't have too much benefits. It seems your example is different, if you really have 120 different tables, and all you need is simple CRUD operations then of course having that abstract repository would make your life easier.

**Comment by jdelafon** [comment]
While it would have been more elegant to complete the generic Repository, I ended up thinking that since this works perfectly well:

```
def insert(table: String, id: Int): Future[Int] = db run sqlu"delete from #$table where id=$id"
```

there was no good incentive to drive oneself crazy with implicits and bugs ignored by the slick team (they basically answer "refactor so that it works").

By the way, I also had lots of issues with inserts when you cannot instantiate the table component explicitly (i.e. you get the table name in the url and must write a generic table component factory). The best way was to make the `insert` method of the Repository _abstract_, and add a concrete `insert` implementation in each table component. This is because it is really hard to create a row model element if you can't call its specific constructor directly (I spent about 10 hours trying with all these `_1$u#TableElementRow` and gave up the generic way).

**Comment by voidcontext** [comment]
I just pushed the generic delete method. It is not nice, as I had to manually implement what should be done by implicit conversion but it does work.

**Comment by jdelafon** [comment]
Impressive, thanks. 
(I would have added a code comment to explain why that weird piece of code is necessary.)
This project is super useful.

**Comment by voidcontext** [comment]
Adding the comment is definitely a good idea, I'll add it. Thanks.

I'm glad if it could help a little bit :)

**Comment by jdelafon** [comment]
Actually the problem can be solved without a hack by replacing the `AbstractTable[_]` type in Repository.scala by 

    <driver>.profile.api.Table

like in `slick.driver.MySQLDriver.profile.api.Table`.
So the signature became for me

    Repository[T <: Table[R], R, I: BaseTypedType]

Then you have the missing implicits.
A very good example of a Play Generic DAO implementation for Slick 3.1+ can be found there:

https://github.com/bravegag/play-authenticate-usage-scala/blob/master/app/dao/generic/GenericDao.scala
